sudo: required
services:
  - docker

before_install:
  - docker build -t bogdangale/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true bogdangale/react-test npm test

after_success:
  - docker build -t bogdangale/multi-client ./client
  - docker build -t bogdangale/multi-nginx ./nginx
  - docker build -t bogdangale/multi-server ./server
  - docker build -t bogdangale/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push bogdangale/multi-client
  - docker push bogdangale/multi-nginx
  - docker push bogdangale/multi-server
  - docker push bogdangale/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'eu-central-1'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-eu-central-1-053241410773'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY